sudo: false
language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
- '9'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: Duwfzd1XIvVLFqFABGPx+iVx1wVJqY0drK4r5pp0yutniocn6A3GP1TmeDmGYx/feUJ5RRBZ3ecPL9i2jxuft7GVHOEV+Ie4iqfVyu9h0ZTAakSzXB9ZkTA7A7aFtiar3ik1XaRHo6Y+Pb7Kml6xNtWHVZwseOETNAzLY2GFUYo=
  email:
    recipients:
      secure: RVriCR4WN+lgiGqLf4YsUJsFhOvrHsmf9PXHbpgKTE0uUQ7f6EGFk8Bv/PDdsIqz9TXU5tfarN68Criyk3Lymma5VlqIKZhRbBXdM+87LNz+9bsPOF53ylaIgwVHhn24hzT7sxSAOCwghFNFjFGTjl05OPnRkEijHSr04CGXaa4=
